insert into omeka_multilanguage_translations (record_id, element_id, record_type, locale_code, text, translation)
SELECT record_id, element_id, record_type, 'pt_BR', text, text
FROM omeka_multilanguage_translations
WHERE record_type = 'Item'
order by record_id, element_id




update omeka_element_texts set text = 'Rascunho de carta para o senhor Pâtier' where id = 185;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Tiedman' where id = 195;
update omeka_element_texts set text = 'Prece - 1857 [1]' where id = 201;
update omeka_element_texts set text = 'Carta para o senhor chefe de polícia' where id = 207;
update omeka_element_texts set text = 'Prece - 1857 [4]' where id = 213;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Gassier' where id = 219;
update omeka_element_texts set text = 'Rascunho de carta para o Doutor Francisco Antônio Pereira Rocha' where id = 225;
update omeka_element_texts set text = 'Evocação' where id = 231;
update omeka_element_texts set text = 'Prece' where id = 237;
update omeka_element_texts set text = 'Evocação' where id = 243;
update omeka_element_texts set text = 'Prece' where id = 250;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Thiry' where id = 256;
update omeka_element_texts set text = 'Cópia de carta para a senhora Hanin Leblanc' where id = 262;
update omeka_element_texts set text = 'Carta para o senhor Sabò' where id = 268;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Varey' where id = 274;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Louis Jourdan' where id = 280;
update omeka_element_texts set text = 'Nota - 1864[?]' where id = 286;
update omeka_element_texts set text = 'Rascunho de carta para a senhora Ebert' where id = 292;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Vincent' where id = 298;
update omeka_element_texts set text = 'Rascunho de carta para [?]' where id = 304;
update omeka_element_texts set text = 'Carta do senhor Cordurié' where id = 310;
update omeka_element_texts set text = 'Rascunho de carta para [?]' where id = 316;
update omeka_element_texts set text = 'Rascunho de carta para [?]' where id = 322;
update omeka_element_texts set text = 'Rascunho de carta para senhora Lair' where id = 328;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Augustin Babin' where id = 334;
update omeka_element_texts set text = 'Rascunho de carta para [?]' where id = 340;
update omeka_element_texts set text = 'Rascunho de carta para o senhor R. Bermoy' where id = 346;
update omeka_element_texts set text = 'Rascunho de carta para a senhora Bouillant' where id = 352;
update omeka_element_texts set text = 'Rascunho de carta para [?]' where id = 358;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Houat' where id = 364;
update omeka_element_texts set text = 'Carta do senhor H. Georges' where id = 580;
update omeka_element_texts set text = 'Rascunho de carta para um Irmão Espírita' where id = 586;
update omeka_element_texts set text = 'Fragmento' where id = 589;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Villeneuve' where id = 592;
update omeka_element_texts set text = 'Cópia de carta para o senhor Jourdan' where id = 595;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Dumas' where id = 598;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Dalmazzo' where id = 601;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Matrat' where id = 604;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Dijoud' where id = 607;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Boudou' where id = 610;
update omeka_element_texts set text = 'Rascunho de carta para a senhora Forge' where id = 613;
update omeka_element_texts set text = 'Rascunho de carta para o senhor <Plenet>' where id = 616;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Sabò' where id = 619;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Edoux' where id = 622;
update omeka_element_texts set text = 'Cópia de carta da senhora Foulon para a senhora Amélie Boudet' where id = 625;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Ganipel' where id = 628;
update omeka_element_texts set text = 'Rascunho de carta para [?]' where id = 631;
update omeka_element_texts set text = 'Rascunho de carta para o senhor Rousset' where id = 850;
update omeka_element_texts set text = 'Carta para o senhor Lourrain' where id = 974;
update omeka_element_texts set text = 'Carta para o senhor Philippe' where id = 987;
update omeka_element_texts set text = 'Psicografia - Espírito: Alfred Mitchell / Michell' where id = 1003;
update omeka_element_texts set text = 'Psicografia - Espírito: Montaigne / Médium: Desliens' where id = 1015;
update omeka_element_texts set text = 'Psicografia - Espírito: um Espírito / Médium: Caussin' where id = 1026;
update omeka_element_texts set text = 'Carta do senhor Leymarie para Allan Kardec' where id = 1037;
update omeka_element_texts set text = 'Psicografia - Médium: Desliens / Espírito: Didier' where id = 1048;
update omeka_element_texts set text = 'Amelie Boudet - Foto 01' where id = 1076;
update omeka_element_texts set text = 'Amelie Boudet - Foto 03' where id = 1082;
update omeka_element_texts set text = 'Amelie Boudet - Foto 04' where id = 1087;
update omeka_element_texts set text = 'Allan Kardec - Foto 01' where id = 1092;
update omeka_element_texts set text = 'Allan Kardec - Foto 02' where id = 1097;
update omeka_element_texts set text = 'Allan Kardec - Foto 03' where id = 1102;
update omeka_element_texts set text = 'Allan Kardec - Foto 04' where id = 1107;
update omeka_element_texts set text = 'Família Leymarie - Foto 01' where id = 1112;
update omeka_element_texts set text = 'Marina Leymarie/Maria Duclos -Foto 01' where id = 1117;
update omeka_element_texts set text = 'Pierre-Gaëtan Leymarie - Foto 01' where id = 1122;
update omeka_element_texts set text = 'Allan Kardec - Litografia 01' where id = 1127;
update omeka_element_texts set text = 'Allan Kardec - Litografia 02' where id = 1132;
update omeka_element_texts set text = 'Psicografia - Médium: Lammenais/ Espírito: Didier' where id = 1161;
update omeka_element_texts set text = 'Psicografia Diálogo -  Médium: Desliens / Espírito: Anônimo' where id = 1169;
update omeka_element_texts set text = 'Escritura - Amélie Boudet' where id = 1172;
update omeka_element_texts set text = 'Discurso - Amélie Boudet' where id = 1175;
update omeka_element_texts set text = 'Discurso - Allan Kardec' where id = 1181;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1238;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1243;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1248;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1253;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1258;
update omeka_element_texts set text = 'Carta de [?] para Amélie Gabrielle Boudet' where id = 1263;
update omeka_element_texts set text = 'Discurso Amélie Boudet' where id = 1268;
update omeka_element_texts set text = 'Carta de [?] para Amélie Gabrielle Boudet' where id = 1273;
update omeka_element_texts set text = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet' where id = 1278;
update omeka_element_texts set text = 'Discurso Amélie Boudet' where id = 1283;
update omeka_element_texts set text = 'Discurso Allan Kardec' where id = 1288;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1293;
update omeka_element_texts set text = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet' where id = 1298;
update omeka_element_texts set text = 'Discurso Allan Kardec' where id = 1303;
update omeka_element_texts set text = 'Discurso Allan Kardec' where id = 1308;
update omeka_element_texts set text = 'Discurso Allan Kardec' where id = 1313;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1318;
update omeka_element_texts set text = 'Caderno de cartas - Sociedade Parisiense de Estudos Espíritas' where id = 1323;
update omeka_element_texts set text = 'Carta de Amélie Gabrielle Boudet' where id = 1328;
update omeka_element_texts set text = 'Carta de Amélie Gabrielle Boudet' where id = 1333;
update omeka_element_texts set text = 'Carta de Amélie Gabrielle Boudet' where id = 1338;
update omeka_element_texts set text = 'Carta de Amélie Gabrielle Boudet' where id = 1343;
update omeka_element_texts set text = 'Carta de Amélie Gabrielle Boudet' where id = 1353;
update omeka_element_texts set text = 'Comunicação - Espírito: Lamennais - Médium: Didier' where id = 1358;
update omeka_element_texts set text = 'Comunicação' where id = 1363;
update omeka_element_texts set text = 'Comunicação - Espírito: Sanson - Médium: Desliens' where id = 1368;
update omeka_element_texts set text = 'Comunicação - Espírito: Anônimo - Médium: Auget Chédeaux' where id = 1373;
update omeka_element_texts set text = 'Comunicação - Espírito: Anônimo - Médium: Senhor Morin' where id = 1378;
update omeka_element_texts set text = 'Comunicação' where id = 1383;
update omeka_element_texts set text = 'Comunicação' where id = 1388;
update omeka_element_texts set text = 'Comunicação' where id = 1393;
update omeka_element_texts set text = 'Comunicação - Espírito: Pierre-Paul Didier - Médium: Armand Desliens' where id = 1398;
update omeka_element_texts set text = 'Diálogo Comunicação - Allan Kardec' where id = 1403;
update omeka_element_texts set text = 'Título de propriedade - Amélie Gabrielle Boudet' where id = 1408;
update omeka_element_texts set text = 'Carta Círculo Internacional - Allan Kardec' where id = 1413;
update omeka_element_texts set text = 'Carta Membro Associado Livre - Allan Kardec' where id = 1418;
update omeka_element_texts set text = 'Carta Membro Titular - Allan Kardec' where id = 1422;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 1483;
update omeka_element_texts set text = 'Discurso de Allan Kardec' where id = 1554;
update omeka_element_texts set text = 'Prece de Allan Kardec' where id = 1561;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1568;
update omeka_element_texts set text = 'Carta de Hipolite Rivail  para Amélie Boudet' where id = 1575;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1582;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1590;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1597;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1604;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1611;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1619;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1627;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1635;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1643;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1651;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1659;
update omeka_element_texts set text = 'Carta de Allan Kardec para Amélie Boudet' where id = 1667;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1675;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1683;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1691;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1699;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1707;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1715;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1723;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1731;
update omeka_element_texts set text = 'Carta de Jeanne Louise Rivail para Amélie Boudet' where id = 1739;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1747;
update omeka_element_texts set text = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 1755;


SELECT concat ('update omeka_multilanguage_translations set text = ''', e.text, ''', translation = ''',e.text,''' where id = ',t.id,';)
FROM omeka_multilanguage_translations t
JOIN omeka_element_texts e on (e.record_id = t.record_id)
where t.element_id = 50
and e.element_id=50
and t.locale_code='pt_BR'
and t.record_type='Item'

update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Pâtier', translation = 'Rascunho de carta para o senhor Pâtier' where id = 497;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Tiedman', translation = 'Rascunho de carta para o senhor Tiedman' where id = 500;
update omeka_multilanguage_translations set text = 'Prece - 1857 [1]', translation = 'Prece - 1857 [1]' where id = 503;
update omeka_multilanguage_translations set text = 'Carta para o senhor chefe de polícia', translation = 'Carta para o senhor chefe de polícia' where id = 506;
update omeka_multilanguage_translations set text = 'Prece - 1857 [4]', translation = 'Prece - 1857 [4]' where id = 509;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Gassier', translation = 'Rascunho de carta para o senhor Gassier' where id = 512;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o Doutor Francisco Antônio Pereira Rocha', translation = 'Rascunho de carta para o Doutor Francisco Antônio Pereira Rocha' where id = 515;
update omeka_multilanguage_translations set text = 'Evocação', translation = 'Evocação' where id = 518;
update omeka_multilanguage_translations set text = 'Prece', translation = 'Prece' where id = 521;
update omeka_multilanguage_translations set text = 'Evocação', translation = 'Evocação' where id = 524;
update omeka_multilanguage_translations set text = 'Prece', translation = 'Prece' where id = 527;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Thiry', translation = 'Rascunho de carta para o senhor Thiry' where id = 530;
update omeka_multilanguage_translations set text = 'Cópia de carta para a senhora Hanin Leblanc', translation = 'Cópia de carta para a senhora Hanin Leblanc' where id = 533;
update omeka_multilanguage_translations set text = 'Carta para o senhor Sabò', translation = 'Carta para o senhor Sabò' where id = 536;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Varey', translation = 'Rascunho de carta para o senhor Varey' where id = 539;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Louis Jourdan', translation = 'Rascunho de carta para o senhor Louis Jourdan' where id = 542;
update omeka_multilanguage_translations set text = 'Nota - 1864[?]', translation = 'Nota - 1864[?]' where id = 545;
update omeka_multilanguage_translations set text = 'Rascunho de carta para a senhora Ebert', translation = 'Rascunho de carta para a senhora Ebert' where id = 548;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Vincent', translation = 'Rascunho de carta para o senhor Vincent' where id = 551;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Rascunho de carta para [?]' where id = 554;
update omeka_multilanguage_translations set text = 'Carta do senhor Cordurié', translation = 'Carta do senhor Cordurié' where id = 557;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Rascunho de carta para [?]' where id = 560;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Rascunho de carta para [?]' where id = 563;
update omeka_multilanguage_translations set text = 'Rascunho de carta para senhora Lair', translation = 'Rascunho de carta para senhora Lair' where id = 566;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Augustin Babin', translation = 'Rascunho de carta para o senhor Augustin Babin' where id = 569;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Rascunho de carta para [?]' where id = 572;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor R. Bermoy', translation = 'Rascunho de carta para o senhor R. Bermoy' where id = 575;
update omeka_multilanguage_translations set text = 'Rascunho de carta para a senhora Bouillant', translation = 'Rascunho de carta para a senhora Bouillant' where id = 578;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Rascunho de carta para [?]' where id = 581;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Houat', translation = 'Rascunho de carta para o senhor Houat' where id = 584;
update omeka_multilanguage_translations set text = 'Carta do senhor H. Georges', translation = 'Carta do senhor H. Georges' where id = 587;
update omeka_multilanguage_translations set text = 'Rascunho de carta para um Irmão Espírita', translation = 'Rascunho de carta para um Irmão Espírita' where id = 590;
update omeka_multilanguage_translations set text = 'Fragmento', translation = 'Fragmento' where id = 593;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Villeneuve', translation = 'Rascunho de carta para o senhor Villeneuve' where id = 596;
update omeka_multilanguage_translations set text = 'Cópia de carta para o senhor Jourdan', translation = 'Cópia de carta para o senhor Jourdan' where id = 599;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Dumas', translation = 'Rascunho de carta para o senhor Dumas' where id = 602;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Dalmazzo', translation = 'Rascunho de carta para o senhor Dalmazzo' where id = 605;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Matrat', translation = 'Rascunho de carta para o senhor Matrat' where id = 608;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Dijoud', translation = 'Rascunho de carta para o senhor Dijoud' where id = 611;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Boudou', translation = 'Rascunho de carta para o senhor Boudou' where id = 614;
update omeka_multilanguage_translations set text = 'Rascunho de carta para a senhora Forge', translation = 'Rascunho de carta para a senhora Forge' where id = 617;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor <Plenet>', translation = 'Rascunho de carta para o senhor <Plenet>' where id = 620;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Sabò', translation = 'Rascunho de carta para o senhor Sabò' where id = 623;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Edoux', translation = 'Rascunho de carta para o senhor Edoux' where id = 626;
update omeka_multilanguage_translations set text = 'Cópia de carta da senhora Foulon para a senhora Amélie Boudet', translation = 'Cópia de carta da senhora Foulon para a senhora Amélie Boudet' where id = 629;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Ganipel', translation = 'Rascunho de carta para o senhor Ganipel' where id = 632;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Rascunho de carta para [?]' where id = 635;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Rousset', translation = 'Rascunho de carta para o senhor Rousset' where id = 638;
update omeka_multilanguage_translations set text = 'Carta para o senhor Lourrain', translation = 'Carta para o senhor Lourrain' where id = 641;
update omeka_multilanguage_translations set text = 'Carta para o senhor Philippe', translation = 'Carta para o senhor Philippe' where id = 644;
update omeka_multilanguage_translations set text = 'Psicografia - Espírito: Alfred Mitchell / Michell', translation = 'Psicografia - Espírito: Alfred Mitchell / Michell' where id = 647;
update omeka_multilanguage_translations set text = 'Psicografia - Espírito: Montaigne / Médium: Desliens', translation = 'Psicografia - Espírito: Montaigne / Médium: Desliens' where id = 650;
update omeka_multilanguage_translations set text = 'Psicografia - Espírito: um Espírito / Médium: Caussin', translation = 'Psicografia - Espírito: um Espírito / Médium: Caussin' where id = 653;
update omeka_multilanguage_translations set text = 'Carta do senhor Leymarie para Allan Kardec', translation = 'Carta do senhor Leymarie para Allan Kardec' where id = 656;
update omeka_multilanguage_translations set text = 'Psicografia - Médium: Desliens / Espírito: Didier', translation = 'Psicografia - Médium: Desliens / Espírito: Didier' where id = 659;
update omeka_multilanguage_translations set text = 'Amelie Boudet - Foto 01', translation = 'Amelie Boudet - Foto 01' where id = 492;
update omeka_multilanguage_translations set text = 'Amelie Boudet - Foto 03', translation = 'Amelie Boudet - Foto 03' where id = 489;
update omeka_multilanguage_translations set text = 'Amelie Boudet - Foto 04', translation = 'Amelie Boudet - Foto 04' where id = 486;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 01', translation = 'Allan Kardec - Foto 01' where id = 483;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 02', translation = 'Allan Kardec - Foto 02' where id = 480;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 03', translation = 'Allan Kardec - Foto 03' where id = 477;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 04', translation = 'Allan Kardec - Foto 04' where id = 474;
update omeka_multilanguage_translations set text = 'Família Leymarie - Foto 01', translation = 'Família Leymarie - Foto 01' where id = 471;
update omeka_multilanguage_translations set text = 'Marina Leymarie/Maria Duclos -Foto 01', translation = 'Marina Leymarie/Maria Duclos -Foto 01' where id = 468;
update omeka_multilanguage_translations set text = 'Pierre-Gaëtan Leymarie - Foto 01', translation = 'Pierre-Gaëtan Leymarie - Foto 01' where id = 465;
update omeka_multilanguage_translations set text = 'Allan Kardec - Litografia 01', translation = 'Allan Kardec - Litografia 01' where id = 462;
update omeka_multilanguage_translations set text = 'Allan Kardec - Litografia 02', translation = 'Allan Kardec - Litografia 02' where id = 459;
update omeka_multilanguage_translations set text = 'Psicografia - Médium: Lammenais/ Espírito: Didier', translation = 'Psicografia - Médium: Lammenais/ Espírito: Didier' where id = 456;
update omeka_multilanguage_translations set text = 'Psicografia Diálogo -  Médium: Desliens / Espírito: Anônimo', translation = 'Psicografia Diálogo -  Médium: Desliens / Espírito: Anônimo' where id = 447;
update omeka_multilanguage_translations set text = 'Escritura - Amélie Boudet', translation = 'Escritura - Amélie Boudet' where id = 444;
update omeka_multilanguage_translations set text = 'Discurso - Amélie Boudet', translation = 'Discurso - Amélie Boudet' where id = 441;
update omeka_multilanguage_translations set text = 'Discurso - Allan Kardec', translation = 'Discurso - Allan Kardec' where id = 435;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 728;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 726;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 724;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 738;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 722;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 720;
update omeka_multilanguage_translations set text = 'Carta de [?] para Amélie Gabrielle Boudet', translation = 'Carta de [?] para Amélie Gabrielle Boudet' where id = 718;
update omeka_multilanguage_translations set text = 'Discurso Amélie Boudet', translation = 'Discurso Amélie Boudet' where id = 716;
update omeka_multilanguage_translations set text = 'Carta de [?] para Amélie Gabrielle Boudet', translation = 'Carta de [?] para Amélie Gabrielle Boudet' where id = 714;
update omeka_multilanguage_translations set text = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet', translation = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet' where id = 712;
update omeka_multilanguage_translations set text = 'Discurso Amélie Boudet', translation = 'Discurso Amélie Boudet' where id = 710;
update omeka_multilanguage_translations set text = 'Discurso Amélie Boudet', translation = 'Discurso Amélie Boudet' where id = 745;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discurso Allan Kardec' where id = 708;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 706;
update omeka_multilanguage_translations set text = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet', translation = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet' where id = 704;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discurso Allan Kardec' where id = 702;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discurso Allan Kardec' where id = 700;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discurso Allan Kardec' where id = 698;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 696;
update omeka_multilanguage_translations set text = 'Caderno de cartas - Sociedade Parisiense de Estudos Espíritas', translation = 'Caderno de cartas - Sociedade Parisiense de Estudos Espíritas' where id = 694;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Carta de Amélie Gabrielle Boudet' where id = 692;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Carta de Amélie Gabrielle Boudet' where id = 690;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Carta de Amélie Gabrielle Boudet' where id = 688;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Carta de Amélie Gabrielle Boudet' where id = 686;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Carta de Amélie Gabrielle Boudet' where id = 682;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Lamennais - Médium: Didier', translation = 'Comunicação - Espírito: Lamennais - Médium: Didier' where id = 680;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 678;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 736;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Sanson - Médium: Desliens', translation = 'Comunicação - Espírito: Sanson - Médium: Desliens' where id = 676;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Anônimo - Médium: Auget Chédeaux', translation = 'Comunicação - Espírito: Anônimo - Médium: Auget Chédeaux' where id = 674;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Anônimo - Médium: Senhor Morin', translation = 'Comunicação - Espírito: Anônimo - Médium: Senhor Morin' where id = 672;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 670;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 734;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 668;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 732;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 666;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Comunicação' where id = 730;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Pierre-Paul Didier - Médium: Armand Desliens', translation = 'Comunicação - Espírito: Pierre-Paul Didier - Médium: Armand Desliens' where id = 664;
update omeka_multilanguage_translations set text = 'Diálogo Comunicação - Allan Kardec', translation = 'Diálogo Comunicação - Allan Kardec' where id = 662;
update omeka_multilanguage_translations set text = 'Título de propriedade - Amélie Gabrielle Boudet', translation = 'Título de propriedade - Amélie Gabrielle Boudet' where id = 660;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Carta de Allan Kardec para Amélie Gabrielle Boudet' where id = 742;
update omeka_multilanguage_translations set text = 'Discurso de Allan Kardec', translation = 'Discurso de Allan Kardec' where id = 750;
update omeka_multilanguage_translations set text = 'Prece de Allan Kardec', translation = 'Prece de Allan Kardec' where id = 753;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 756;
update omeka_multilanguage_translations set text = 'Carta de Hipolite Rivail  para Amélie Boudet', translation = 'Carta de Hipolite Rivail  para Amélie Boudet' where id = 759;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 762;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 765;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 768;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 771;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 774;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 777;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 780;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 783;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 786;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 789;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 792;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Carta de Allan Kardec para Amélie Boudet' where id = 795;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 798;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 801;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 804;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 807;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 810;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 813;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 816;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 819;
update omeka_multilanguage_translations set text = 'Carta de Jeanne Louise Rivail para Amélie Boudet', translation = 'Carta de Jeanne Louise Rivail para Amélie Boudet' where id = 828;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 822;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Carta de Hypolite Rivail para Amélie Boudet' where id = 825;


SELECT concat ('update omeka_multilanguage_translations set text = ''', e.text, ''', translation = ''',t.translation,''' where id = ',t.id,';)
FROM omeka_multilanguage_translations t
JOIN omeka_element_texts e on (e.record_id = t.record_id)
where t.element_id = 50
and e.element_id=50
and t.locale_code='fr'
and t.record_type='Item'

update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Pâtier', translation = 'Brouillon d’une lettre à Monsieur Pâtier' where id = 78;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Tiedman', translation = 'Brouillon d’une lettre à Monsieur Tiedemann' where id = 81;
update omeka_multilanguage_translations set text = 'Prece - 1857 [1]', translation = 'Prière - 1857 [1]' where id = 84;
update omeka_multilanguage_translations set text = 'Carta para o senhor chefe de polícia', translation = 'Lettre à Monsieur le Préfet de police' where id = 87;
update omeka_multilanguage_translations set text = 'Prece - 1857 [4]', translation = 'Prière - 1857 [4]' where id = 90;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Gassier', translation = 'Brouillon d’une lettre à Monsieur Gassier' where id = 93;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o Doutor Francisco Antônio Pereira Rocha', translation = 'Brouillon d’une lettre au Docteur Francisco Antônio Pereira Rocha' where id = 96;
update omeka_multilanguage_translations set text = 'Evocação', translation = 'Évocation' where id = 99;
update omeka_multilanguage_translations set text = 'Prece', translation = 'Prière' where id = 102;
update omeka_multilanguage_translations set text = 'Evocação', translation = 'Évocation' where id = 105;
update omeka_multilanguage_translations set text = 'Prece', translation = 'Prière' where id = 108;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Thiry', translation = 'Brouillon d’une lettre à Monsieur Thiry' where id = 111;
update omeka_multilanguage_translations set text = 'Cópia de carta para a senhora Hanin Leblanc', translation = 'Copie d’une lettre à Madame Hanin Leblanc' where id = 114;
update omeka_multilanguage_translations set text = 'Carta para o senhor Sabò', translation = 'Lettre à Monsieur Sabò' where id = 117;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Varey', translation = 'Brouillon d’une lettre à Monsieur Varey' where id = 120;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Louis Jourdan', translation = 'Brouillon d’une lettre à Monsieur Louis Jourdan' where id = 123;
update omeka_multilanguage_translations set text = 'Nota - 1864[?]', translation = 'Note - 1864[?]' where id = 126;
update omeka_multilanguage_translations set text = 'Rascunho de carta para a senhora Ebert', translation = 'Brouillon d’une lettre à Madame Ebert' where id = 129;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Vincent', translation = 'Brouillon d’une lettre à Monsieur Vincent' where id = 132;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Brouillon d’une lettre à [?]' where id = 135;
update omeka_multilanguage_translations set text = 'Carta do senhor Cordurié', translation = 'Lettre de Monsieur Cordurié' where id = 138;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Brouillon d’une lettre à [?]' where id = 141;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Brouillon d’une lettre à [?]' where id = 144;
update omeka_multilanguage_translations set text = 'Rascunho de carta para senhora Lair', translation = 'Brouillon d’une lettre à Madame Lair' where id = 147;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Augustin Babin', translation = 'Brouillon d’une lettre à Monsieur Augustin Babin' where id = 150;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Brouillon d’une lettre à [?]' where id = 153;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor R. Bermoy', translation = 'Brouillon d’une lettre à Monsieur R. Bermoy' where id = 156;
update omeka_multilanguage_translations set text = 'Rascunho de carta para a senhora Bouillant', translation = 'Brouillon d’une lettre à Madame Bouillant' where id = 159;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Brouillon d’une lettre à [?]' where id = 162;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Houat', translation = 'Brouillon d’une lettre à Monsieur Houat' where id = 165;
update omeka_multilanguage_translations set text = 'Carta do senhor H. Georges', translation = 'Lettre à Monsieur H. Georges' where id = 168;
update omeka_multilanguage_translations set text = 'Rascunho de carta para um Irmão Espírita', translation = 'Brouillon d’une lettre à un frère spirite' where id = 171;
update omeka_multilanguage_translations set text = 'Fragmento', translation = 'Fragment' where id = 174;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Villeneuve', translation = 'Brouillon d’une lettre à Monsieur Villeneuve' where id = 177;
update omeka_multilanguage_translations set text = 'Cópia de carta para o senhor Jourdan', translation = 'Copie d’une lettre à Monsieur Jourdan' where id = 180;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Dumas', translation = 'Brouillon d’une lettre à Monsieur Dumas' where id = 183;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Dalmazzo', translation = 'Brouillon d’une lettre à Monsieur Dalmazzo' where id = 186;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Matrat', translation = 'Brouillon d’une lettre à Monsieur Matrat' where id = 189;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Dijoud', translation = 'Brouillon d’une lettre à Monsieur Dijoud' where id = 192;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Boudou', translation = 'Brouillon d’une lettre à Monsieur Boudou' where id = 195;
update omeka_multilanguage_translations set text = 'Rascunho de carta para a senhora Forge', translation = 'Brouillon d’une lettre à Madame Forge' where id = 198;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor <Plenet>', translation = 'Brouillon d’une lettre à Monsieur <Plenet>' where id = 201;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Sabò', translation = 'Brouillon d’une lettre à Monsieur Sabò' where id = 204;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Edoux', translation = 'Brouillon d’une lettre à Monsieur Edoux' where id = 207;
update omeka_multilanguage_translations set text = 'Cópia de carta da senhora Foulon para a senhora Amélie Boudet', translation = 'Copie d’une lettre de Madame Foulon à Madame Amélie Boudet' where id = 210;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Ganipel', translation = 'Brouillon d’une lettre à Monsieur Ganipel' where id = 213;
update omeka_multilanguage_translations set text = 'Rascunho de carta para [?]', translation = 'Brouillon d’une lettre à [?]' where id = 216;
update omeka_multilanguage_translations set text = 'Rascunho de carta para o senhor Rousset', translation = 'Brouillon d’une lettre à Monsieur Rousset' where id = 219;
update omeka_multilanguage_translations set text = 'Carta para o senhor Lourrain', translation = 'Lettre à Monsieur Lourrain' where id = 222;
update omeka_multilanguage_translations set text = 'Carta para o senhor Philippe', translation = 'Lettre à Monsieur Philippe' where id = 225;
update omeka_multilanguage_translations set text = 'Psicografia - Espírito: Alfred Mitchell / Michell', translation = 'Psychographie - Medium: Anonyme/Esprit: Alfred Mitchell/Michell' where id = 228;
update omeka_multilanguage_translations set text = 'Psicografia - Espírito: Montaigne / Médium: Desliens', translation = 'Psychographie - Medium: Desliens/Esprit: Montaigne' where id = 231;
update omeka_multilanguage_translations set text = 'Psicografia - Espírito: um Espírito / Médium: Caussin', translation = 'Psychographie - Medium: Caussin/Esprit: un Esprit' where id = 234;
update omeka_multilanguage_translations set text = 'Carta do senhor Leymarie para Allan Kardec', translation = 'Lettre Monsieur Leymarie à Allan Kardec' where id = 237;
update omeka_multilanguage_translations set text = 'Psicografia - Médium: Desliens / Espírito: Didier', translation = 'Psychographie - Medium: Desliens/Esprit: Didier' where id = 241;
update omeka_multilanguage_translations set text = 'Amelie Boudet - Foto 01', translation = 'Amelie Boudet - Photographier 01' where id = 73;
update omeka_multilanguage_translations set text = 'Amelie Boudet - Foto 03', translation = 'Amelie Boudet - Photographier 03' where id = 70;
update omeka_multilanguage_translations set text = 'Amelie Boudet - Foto 04', translation = 'Amelie Boudet - Photographier 04' where id = 67;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 01', translation = 'Allan Kardec - Photographier 01' where id = 64;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 02', translation = 'Allan Kardec - Photographier 02' where id = 61;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 03', translation = 'Allan Kardec - Photographier 03' where id = 58;
update omeka_multilanguage_translations set text = 'Allan Kardec - Foto 04', translation = 'Allan Kardec - Photographier 04' where id = 55;
update omeka_multilanguage_translations set text = 'Família Leymarie - Foto 01', translation = 'Família Leymarie - Photographier 01' where id = 52;
update omeka_multilanguage_translations set text = 'Marina Leymarie/Maria Duclos -Foto 01', translation = 'Marina Leymarie/Maria Duclos - Photographier 01' where id = 49;
update omeka_multilanguage_translations set text = 'Pierre-Gaëtan Leymarie - Foto 01', translation = 'Pierre-Gaëtan Leymarie - Photographier 01' where id = 46;
update omeka_multilanguage_translations set text = 'Allan Kardec - Litografia 01', translation = 'Allan Kardec - Lithographier 01' where id = 43;
update omeka_multilanguage_translations set text = 'Allan Kardec - Litografia 02', translation = 'Allan Kardec - Lithographier 02' where id = 40;
update omeka_multilanguage_translations set text = 'Psicografia - Médium: Lammenais/ Espírito: Didier', translation = 'Psychographie - Medium: Lammenais/Esprit: Didier' where id = 37;
update omeka_multilanguage_translations set text = 'Psicografia Diálogo -  Médium: Desliens / Espírito: Anônimo', translation = 'Psychographie Dialogue - Medium: Desliens/Esprit: Anonyme' where id = 28;
update omeka_multilanguage_translations set text = 'Escritura - Amélie Boudet', translation = 'Écriture - Amélie Boudet' where id = 25;
update omeka_multilanguage_translations set text = 'Discurso - Amélie Boudet', translation = 'Discours - Amélie Boudet' where id = 22;
update omeka_multilanguage_translations set text = 'Discurso - Allan Kardec', translation = 'Discours - Allan Kardec' where id = 16;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 310;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 308;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 306;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 320;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 304;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 302;
update omeka_multilanguage_translations set text = 'Carta de [?] para Amélie Gabrielle Boudet', translation = 'Lettre à Amélie Gabrielle Boudet' where id = 300;
update omeka_multilanguage_translations set text = 'Discurso Amélie Boudet', translation = 'Discours d\'Amélie Gabrielle Boudet - 1844' where id = 298;
update omeka_multilanguage_translations set text = 'Carta de [?] para Amélie Gabrielle Boudet', translation = 'Lettre à Amélie Gabrielle Boudet' where id = 296;
update omeka_multilanguage_translations set text = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet', translation = 'Lettre de Julien-Louis Boudet à Amélie Gabrielle Boudet' where id = 294;
update omeka_multilanguage_translations set text = 'Discurso Amélie Boudet', translation = 'Discours d\'Amélie Gabrielle Boudet' where id = 292;
update omeka_multilanguage_translations set text = 'Discurso Amélie Boudet', translation = 'Discours d\'Amélie Gabrielle Boudet' where id = 328;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discousr d\'Allan Kardec' where id = 290;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 288;
update omeka_multilanguage_translations set text = 'Carta de Julien-Louis Boudet para Amélie Gabrielle Boudet', translation = 'Lettre de Julien-Louis Boudet à Amélie Gabrielle Boudet' where id = 286;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discousr d\'Allan Kardec' where id = 284;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discousr d\'Allan Kardec' where id = 282;
update omeka_multilanguage_translations set text = 'Discurso Allan Kardec', translation = 'Discousr d\'Allan Kardec' where id = 280;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 278;
update omeka_multilanguage_translations set text = 'Caderno de cartas - Sociedade Parisiense de Estudos Espíritas', translation = 'Carnet de lettres - Société parisienne d\'études spirites' where id = 276;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Lettre d\'Amélie Gabrielle Boudet' where id = 274;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Lettre d\'Amélie Gabrielle Boudet' where id = 272;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Lettre d\'Amélie Gabrielle Boudet' where id = 270;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Lettre d\'Amélie Gabrielle Boudet' where id = 268;
update omeka_multilanguage_translations set text = 'Carta de Amélie Gabrielle Boudet', translation = 'Lettre à Amélie Gabrielle Boudet' where id = 264;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Lamennais - Médium: Didier', translation = 'Communication - Esprit: Lamennais - Médium: Didier' where id = 262;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 260;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 318;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Sanson - Médium: Desliens', translation = 'Communication - Esprit: Sanson - Médium: Desliens' where id = 258;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Anônimo - Médium: Auget Chédeaux', translation = 'Communication - Esprit: Anônimo - Médium: Auget Chédeaux' where id = 256;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Anônimo - Médium: Senhor Morin', translation = 'Communication - Esprit: Anônimo - Médium: Senhor Morin' where id = 254;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 252;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 316;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 250;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 314;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 248;
update omeka_multilanguage_translations set text = 'Comunicação', translation = 'Communication' where id = 312;
update omeka_multilanguage_translations set text = 'Comunicação - Espírito: Pierre-Paul Didier - Médium: Armand Desliens', translation = 'Communication - Esprit: Pierre-Paul Didier - Médium: Armand Desliens' where id = 246;
update omeka_multilanguage_translations set text = 'Diálogo Comunicação - Allan Kardec', translation = 'Dialogue Communication - Allan Kardec' where id = 244;
update omeka_multilanguage_translations set text = 'Título de propriedade - Amélie Gabrielle Boudet', translation = 'Titre de propriété - Amélie Gabrielle Boudet' where id = 242;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Gabrielle Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Gabrielle Boudet' where id = 325;
update omeka_multilanguage_translations set text = 'Discurso de Allan Kardec', translation = 'Discours d\'Allan Kardec' where id = 333;
update omeka_multilanguage_translations set text = 'Prece de Allan Kardec', translation = 'Prière d\'Allan Kardec' where id = 336;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 339;
update omeka_multilanguage_translations set text = 'Carta de Hipolite Rivail  para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 342;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 345;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 348;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 351;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 354;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 357;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 360;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 363;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 366;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 369;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 372;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 375;
update omeka_multilanguage_translations set text = 'Carta de Allan Kardec para Amélie Boudet', translation = 'Lettre d\'Allan Kardec à Amélie Boudet' where id = 378;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 381;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 384;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 387;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 390;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 393;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 396;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 399;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 402;
update omeka_multilanguage_translations set text = 'Carta de Jeanne Louise Rivail para Amélie Boudet', translation = 'Lettre de Jeanne Louise Rivail à Amélie Boudet' where id = 411;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 405;
update omeka_multilanguage_translations set text = 'Carta de Hypolite Rivail para Amélie Boudet', translation = 'Lettre de Hipolite Rivail à Amélie Boudet' where id = 408;

SELECT concat('update omeka_element_texts set text = ''',text,''' where id = ', id,';')  FROM omeka_element_texts where element_id = 40

update omeka_element_texts set text = '1864/MM/DD' where id = 559;
update omeka_element_texts set text = '1860/MM/DD' where id = 565;
update omeka_element_texts set text = '1857/MM/DD' where id = 571;
update omeka_element_texts set text = '1857/MM/DD' where id = 572;
update omeka_element_texts set text = '1857/MM/DD' where id = 573;
update omeka_element_texts set text = '1857/05/DD' where id = 574;
